config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "/jquery-1" => "pages#jquery_1"
  #get "/jquery-2" => "pages#jquery_2"
  #get "/jquery-3" => "pages#jquery_3"
  #get "/jquery-4" => "pages#jquery_4"
  #get "/jquery-5" => "pages#jquery_5"
  #
  #root "pages#jquery_1"

  resources :posts do
    member do
      #post "like" => "posts#like"
      #post "unlike" => "posts#unlike"
      post :like
      post :unlike
    end
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :content

  belongs_to :user

  has_many :likes, :dependent => :destroy # 级联删除，删除用户时删除该用户所有的点赞
  has_many :liked_users, :through => :likes, :source => :user

  def find_like(user)
    self.likes.where(:user_id => user.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  has_many :likes, :dependent => :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  def display_name
    self.email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :destroy]

  def index
    @posts = Post.order('id DESC').all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save

  end


  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    #redirect_to posts_path
  end

  def like
    @post = Post.find(params[:id])
    unless @post.find_like(current_user)
      Like.create(:user => current_user, :post => @post)
    end
    #redirect_to posts_path
  end

  def unlike
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy

    #redirect_to posts_path
    render "like"
  end

  protected

  def post_params
    params.require(:post).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo16AjaxPostingApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% if flash[:alert] %>
  <%= flash[:alert] %>
<% end %>

<% if current_user %>
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
  <%= link_to('修改密码', edit_registration_path(:user)) %>
<% else %>
  <%= link_to('注册', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
<% end %>

<%= yield %>
</body>
</html>

app/views/pages/jquery_1.html.erb
<p>
  <a id="my-open-click">Click Me</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <a id="my-hide-click">Hide</a>
</div>

<div>
  123
</div>

<script>
    $(function () {
        $("#foo").hide();

        $("#my-open-click").click(function () {
          $("#foo").slideDown();
        })

        $("#my-hide-click").click(function () {
          $("#foo").slideUp();
        })
    })
</script>

app/views/pages/jquery_3.html.erb
<p>
  <a id="my-toggle-click">Toggle</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
    $(function () {
        $("#foo").hide();

        $("#my-toggle-click").hover(function () {
            // $("#foo").toggle();
            $("#foo").slideToggle();
        })
    })
</script>

app/views/pages/jquery_4.html.erb
<p>
  <a id="my-replace-click">Replace</a>
  <a id="my-remove-click">Remove</a>
  <a id="my-remove-all-click">Remove All</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<div class="zoo"><p>a</p></div>
<div class="zoo"><p>b</p></div>
<div class="zoo"><p>c</p></div>

<script>
    $("#my-replace-click").click(function () {
        $("#foo").replaceWith('<div id="foo" style="border: 1px solid green"><p>foo</p></div>')
    })

    $("#my-remove-click").click(function () {
        $("#foo").remove();
    })

    $("#my-remove-all-click").click(function () {
        $(".zoo").remove();
    })
</script>

app/views/pages/jquery_5.html.erb
<p>
  <a id="my-add-class-click">Add Class</a>
  <a id="my-remove-class-click">Remove Class</a>
</p>

<div id="foo">
  <h1>bar</h1>
</div>

<style>
  .error {
    color: red;
  }

  .success {
    color: green;
  }
</style>

<script>
    $(function () {
        $("#my-add-class-click").click(function () {
            $("#foo").removeClass('error');
            $("#foo").addClass('success');
        })

        $("#my-remove-class-click").click(function () {
            $("#foo").removeClass('success');
            $("#foo").addClass('error');
        })
    })
</script>

app/views/posts/_like.html.erb
<% if post.liked_users.any? %>
  <%= post.liked_users.map { |u| u.display_name }.join(",") %>点了赞
<% end %>

<% if current_user %>
  <% if post.find_like(current_user) %>
    <%= link_to "取消赞", unlike_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% else %>
    <%= link_to "赞", like_post_path(post), :method => :post, :remote => true, :class => "btn btn-danger" %>
  <% end %>
  <%= link_to "Delete", post_path(post), :method => :delete, :class => "btn btn-danger", :remote => true %>
<% end %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="panel panel-default">
  <div class="panel-heading"><%= post.user.display_name %></div>
  <div class="panel-body">
    <%= post.content %>

    <div class="text-right">

      <span id="post-like-<%= post.id %>">
        <%= render :partial => "like", :locals => {:post => post} %>
      </span>

    </div>
  </div>
</div>

app/views/posts/create.js.erb
<% if @post.valid? %>
$("#post-list").prepend("<%= j render :partial => "post", :locals => { :post => @post} %>");
$("#post_content").val("")
<% else %>
alert("贴文失败");
<% end %>

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove();

app/views/posts/index.html.erb
<%= form_for Post.new, :remote => true do |f| %>
  <div class="form-group">
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

<div id="post-list">
  <% @posts.each do |post| %>
    <%= render :partial => "post", :locals => { :post => post} %>
  <% end %>
</div>

app/views/posts/like.js.erb
str = "<%= j render :partial => "like", :locals => { :post => @post} %>";
$("#post-like-<%= @post.id %>").html(str);